//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArrivalOrderView
    {
        public string name { get; set; }
        public string status { get; set; }
        public Nullable<bool> isFinished { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public string flightNumber { get; set; }
        public System.DateTime scheduledTime { get; set; }
        public Nullable<double> manni { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public Nullable<long> arrival_id { get; set; }
        public long arrivalFlightId { get; set; }
        public int id { get; set; }
    }
}
